### ISSUE TITLE
generateShortUrl method not working! It always gives me the lengthy URL

### ISSUE THREAD

**Issue by v-pandiarajan-swaas** [BranchMetrics/android-branch-deep-linking#245]
**Link Generated,**
https://6c5g.app.link/?%24identity_id=263905003394173871?channel=Hangouts&feature=sharing&type=0&duration=0&source=android&data=eyJGZWF0dXJlX0lkIjoiMjIzNSIsInNvdXJjZSI6ImFuZHJvaWQiLCIkY29udGVudF90eXBlIjoiIiwiJG9nX2Rlc2NyaXB0aW9uIjoiIiwiJGNhbm9uaWNhbF9pZGVudGlmaWVyIjoiIiwiJGtleXdvcmRzIjpbXSwiJGFsd2F5c19kZWVwbGluayI6InRydWUiLCIkb2dfdGl0bGUiOiJ0aGUraW5mb3JtYXRpb24rY29udGFpbmVkK2luIiwiJGNhbm9uaWNhbF91cmwiOiIiLCIkZXhwX2RhdGUiOiIwIiwiRmVhdHVyZSI6IkRCX1NIQVJFIn0=

**Link Genration Code,**
BranchUniversalObject branchUniversalObject = new BranchUniversalObject();
branchUniversalObject.setTitle("Title");
branchUniversalObject.setContentIndexingMode(BranchUniversalObject.CONTENT_INDEX_MODE.PUBLIC);
branchUniversalObject.addContentMetadata("key1" ,"Test");
LinkProperties linkProperties = new LinkProperties()
                                            .setChannel(resolveInfo.activityInfo.applicationInfo
                                                    .loadLabel(mContext.getPackageManager()).toString())
                                            .setFeature("sharing")
                                            .addControlParameter("$always_deeplink", "true");

**Comment by sojanpr** [comment]
@v-pandiarajan-swaas Thanks for reaching out. 
The  long url is created when there is an error while creating the short url. Can you please make sure  if you are connected to internet and using a correct branch key in your manifest. Also it would be great if you can help us with some debug logs ( please set `io.branch.sdk.TestMode` to `true` in your manifest to get debug logs)

Our awesome support team can help here. In order to get a faster response, could you please email your implementation questions to support@branch.io?

**Comment by EvangelosG** [comment]
As Sojan said, we're happy to help in Support! If you continue to have issues after reading his response, please send your issue to support@branch.io and I'll work with you 1:1.

**Comment by v-pandiarajan-swaas** [comment]
Thank you, @sojanpr. Will check with test mode. But anyway if an error occurred then branch.io must return the null URL instead of long URL.

**Comment by sojanpr** [comment]
@v-pandiarajan-swaas  Thanks for your updates. unfortunately most of our partners  need to get a link 100% of the time in production. Thats why we decided to send a long url in case of any run time error.

Do you think you can check the url format in order to figure out what url is returned, as below

``` branchUniversalObject.generateShortUrl(MainActivity.this, linkProperties, new Branch.BranchLinkCreateListener() {
                    @Override
                    public void onLinkCreate(String url, BranchError error) {
                        if(url.contains("identity_id")) {
                            // url is a long url due to some temp errors
                        }
                        else {
                            // Url is a short link url
                        }
                    }
                });```

**Comment by v-pandiarajan-swaas** [comment]
Thanks @sojanpr, I will include the above the condition. But please confirm if the lengthy URL must contain the key "identity_id", otherwise again it leads to the wrong URL.

**Comment by sojanpr** [comment]
@v-pandiarajan-swaas good that you pointed out this question. The only  one  corner case that can give a long ur without  `identity_id` is while  creating a long link after clearing the preference data. Added an extra check to the above sample. This will handle all cases of long urls. 
Thanks

**Comment by v-pandiarajan-swaas** [comment]
Thanks @sojanpr

**Comment by v-pandiarajan-swaas** [comment]
@sojanpr/ @EvangelosG  I am always getting the error URL. Please help me to fix this issue. Previously It comes correctly but for the last three days didn't. 

**Note**
In test mode, ShortURL generation was working fine. 

Is there any pricing plans?

**FYI**
branch key: key_live_iom1TfqjE2ONMpUY9EocahkcCtnckLq2

**Comment by sojanpr** [comment]
@v-pandiarajan-swaas Branch Deep link service is absolutely free! Since this seems more like a implemantation issue with Branch_Key or package name can we take care of this in the support.  We have an awesome support team who help you fix this very quickly .Could you please email this to support@branch.io

**Comment by v-pandiarajan-swaas** [comment]
@sojanpr Thanks for your reply. This is related to the issue #248. Now it's working fine. If any other assistance needed I will contact your support team.  Special thanks to you for the quick response.

**Comment by VvoidVano** [comment]
Hi
I'm using Branch to create QR image url, but sometimes it didn't work well.  and report: 

Trouble creating a URL. Please specify an event. The request was invalid.

Are there any ways to solve this ? Thank you !
