### ISSUE TITLE
initSession - BranchReferralInitListener Not get Called

### ISSUE THREAD

**Issue by misaelpc** [BranchMetrics/android-branch-deep-linking#249]
Hi, 

Gradle  just update to the latest version 1.12.1

compile 'io.branch.sdk.android:library:1.+'

In this version the call back BranchReferralInitListener never gets called

If I change to version:

compile 'io.branch.sdk.android:library:1.11.3'

It Works fine.

**Comment by sojanpr** [comment]
@misaelpc Really sorry that you are facing this issue. We had an issue with 1.12.0 and we released a  new version 1.12.1 with the fix in the following PR
https://github.com/BranchMetrics/android-branch-deep-linking/issues/246

Basically the issue was caused when calling `initSession` from `onCreate()` method of activity.  Could you please try one more time with 1.12.1

**Comment by sojanpr** [comment]
@misaelpc  seems like issue is same as this https://github.com/BranchMetrics/android-branch-deep-linking/issues/246 and it is solved with 1.12.1. Could you please update if you still have any issues

**Comment by sojanpr** [comment]
@misaelpc  just wanted to check if you are facing this issue .We have found one more really corner case that can contribute this case. The fix has already released with v1.13.1. Thanks for your help

**Comment by misaelpc** [comment]
Hello, with version 1.13.1, works fine, thank you :)
