### ISSUE TITLE
Deep Linking not working on second link clicked

### ISSUE THREAD

**Issue by misaelpc** [BranchMetrics/android-branch-deep-linking#259]
When app its launched from scratch from a branch link, the next time a branch link its clicked, deep link its not working, it does not launch the deep link activity.

However, if the app its not launched from branch link. it works fine

**Comment by aaustin** [comment]
Hey @misaelpc - Thanks much for this note. This sound suspiciously like the Intent is not getting updated!

In the Activity where you call initSession (the routing activity with the `<intent-filter>`), did you override `onNewIntent`? Here's the [docs reference](https://dev.branch.io/getting-started/sdk-integration-guide/guide/android/#start-a-branch-session) and code snippet below for convenience.
```
@Override
public void onNewIntent(Intent intent) {
    this.setIntent(intent);
}
```

**Comment by misaelpc** [comment]
Thank you @aaustin for the quick answer.

`onNewIntent` it its overridden.

Being said that, I'm not seeing that onNewIntent gets called

@Override
   public void onNewIntent(Intent intent) {
       super.onNewIntent(intent);
       Log.d("COM.RJ.LOGINACTIVITY", "onNewIntent");
       this.setIntent(intent);
   }

I'm using a FragmentActivity subclass, as a deep link activity.

**Comment by aaustin** [comment]
That's got to be the problem. Basically, for some reason, Android doesn't update the intent correctly unless you call this code and we need to see the latest intent in order to receive the deep link data when the app is backgrounded.

Can you confirm that the FragmentActivity is configured to receive the intent via the manifest? Like so:
```xml
<activity
    android:name="com.rj.YourFragmentActivity"
    android:label="@string/app_name"
    <!-- Make sure the activity is launched as "singleTask" -->
    android:launchMode="singleTask"
     >
    <intent-filter>
        <action android:name="android.intent.action.MAIN" />
        <category android:name="android.intent.category.LAUNCHER" />
    </intent-filter>

    <intent-filter>
        <data android:scheme="<YOUR URI SCHEME>" />
        <action android:name="android.intent.action.VIEW" />
        <category android:name="android.intent.category.DEFAULT" />
        <category android:name="android.intent.category.BROWSABLE" />
    </intent-filter>
</activity>
```

**Comment by ronaldo-getreveel** [comment]
Same problem here. Method setIntent() is ok, the singleTask lunchMode as well.
Any suggestion?

**Comment by misaelpc** [comment]
Hi @ronaldo-getreveel,

In my case I was missing, the launch mode.
 
In your case  **onNewIntent** its  being called ?

**Comment by sojanpr** [comment]
@misaelpc  Thanks for updating the fix worked for you. @ronaldo-getreveel  is it working after setting the launch mode to "singleTask"

**Comment by ronaldo-getreveel** [comment]
@misaelpc @sojanpr nops, its not working. The `onNewIntent` method is never called. The launch mode is properly defined as `singleTask`.

```
<intent-filter android:autoVerify="true">
    <data android:host="open" android:scheme="myScheme" />
    <action android:name="android.intent.action.VIEW" />
    <category android:name="android.intent.category.DEFAULT" />
    <category android:name="android.intent.category.BROWSABLE" />
    <data android:host="myappLinkProd" android:scheme="https" />
    <data android:host="myappLinkDev" android:scheme="https" />
</intent-filter>
```

The problem is exactly as @misaelpc  described in the first post of this thread. When the app is already opened (doesn't matter if the first opening is from a link or not) the `onNewIntent()` is never called and routing function contains no link info.

**Comment by sojanpr** [comment]
@ronaldo-getreveel  We are trying to reproduce the issue. Will update asap. I would strongly encourage to write to our awesome  integration team (support@branch.io) to get faster response

**Comment by ronaldo-getreveel** [comment]
+ info, the exact behavior that is failing is when I press the "square button" to change from an app to other and then I click on the link. 
If I press the back button until I left the app or the home button and then I click in the link again the `onNewIntent()` is called and it working fine.

**Comment by sojanpr** [comment]
@ronaldo-getreveel just for  confirming, could you please make sure you have `setIntent(intent);` called in `onNewIntent()` method for the  `singleTask` Activity

```@Override
    protected void onNewIntent(Intent intent) {
        super.onNewIntent(intent);
        setIntent(intent);
    }```

**Comment by ronaldo-getreveel** [comment]
Yes, it is properly overridden:

My code:

 ```
@Override
    protected void onNewIntent(Intent intent) {
        super.onNewIntent(intent);
        setIntent(intent);
    }
```

The intent filter:

```
<intent-filter android:autoVerify="true">
    <data android:host="open" android:scheme="myScheme" />
    <action android:name="android.intent.action.VIEW" />
    <category android:name="android.intent.category.DEFAULT" />
    <category android:name="android.intent.category.BROWSABLE" />
    <data android:host="myappLinkProd" android:scheme="https" />
    <data android:host="myappLinkDev" android:scheme="https" />
</intent-filter>
```

My routing activity is the launcher activity too. Could it be the reason it is not working?

**Comment by sojanpr** [comment]
@ronaldo-getreveel Thanks for the details. I could reproduce the issue with a test app. We working on it and update  you asap. Thanks for mentioning this

**Comment by sojanpr** [comment]
@ronaldo-getreveel  A quick check over different version of Android shows that this is a life cycle issue with latest Android. The solution is to change the `LaunchMode` of your deeplinked activity (Launcher activity in your case) to `singleTop` instead of `singleTask`

 In detail the issue is with some android versions having the following  lifecycle methods for lauching a singleTask activity  while an instance of it is already running
`onCreate() -> onStart() -> onNewIntent()`
Where as per the documentation it is supposed to be 
`onNewIntent() -> onStart`

Do you mind giving it a try with `SingleTop` and updating here

**Comment by ronaldo-getreveel** [comment]
Its working but I should implicit call finish() in the deeplink routing activity after the session was inited, otherwise the second time I click in the link it get stucked and onStart() is never called.

**Comment by sojanpr** [comment]
@ronaldo-getreveel Thanks for trying it. 
As you said above, it seems like the easiest and cleaner solution for this issue is to have a `Splash activity` to handle deep link and then open your home or content activity by finishing the splash. That case you can always use `singleTask` and avoid problem of having instance of the same activity.
So could you please try having 

1.SingleTask Splash activity to  receive deep link params
2. Finish splash and launch home activity with deep linked content

    A test application we added for verifying this fix work fine on different Android  versions.

**Comment by ronaldo-getreveel** [comment]
Its working now calling the method `finish()` implicitly. 
Thanks

**Comment by ronaldo-getreveel** [comment]
Hey there, 
Was published any fix for this issue? The problem started to happen again. :)

For marshmallow the newIntent() is called after the onStart().

**Comment by sojanpr** [comment]
@ronaldo-getreveel We have added this fix with V2.0.2 . Could you please try that version

**Comment by sojanpr** [comment]
@ronaldo-getreveel Could you please update if   v2.0.2 solved the above issue?

**Comment by Max01010101010101** [comment]
Yes, is fixed with `singleTop`

**Comment by beast-shubham** [comment]
So I reached out to the Integration team and got a super quick response, which fixed the issue. 

They asked to check the following things - 
1) Are you initializing Branch in your Main/Splash/Launcher Activity?
2) Is your Main/Splash/Launcher activity's launch mode singleTask?
3) Are you overriding onStart() and calling Branch.initSession in it?
4) Are you overriding onNewIntent()?
5) Does the link you are clicking on have the same Branch key as the one you put in your AndroidManifest.xml? (you can append ?debug=1 to the link to see the key)

For me, it was (3) that was the issue. I was doing it in onResume() and changing it to onStart() fixed it! Hope this helps.
