### ISSUE TITLE
BranchUniversalObject.getShortUrl() return long url when called inside AsyncTask

### ISSUE THREAD

**Issue by bubinimara** [BranchMetrics/android-branch-deep-linking#272]
I get a long url when I try to create a short url from an AsyncTask.doInBackground() by calling the method BranchUniversalObject.getShortUrl()

**Comment by sojanpr** [comment]
@bubinimara  BranchUniversalObject.getShortUrl() is internally using anSyncTask for getting the URL since URL creation involves network operation. Async tasks cannot be executed from background thered and thats is the reason for getting a long url.

Could you please try to call `BranchUniversalObject.getShortUrl()` from your `onPreExecute` of your Async task and then use it in your `doInBackGround` method?

**Comment by sojanpr** [comment]
Updated a fix with PR https://github.com/BranchMetrics/android-branch-deep-linking/pull/273
