### ISSUE TITLE
Using singleTask

### ISSUE THREAD

**Issue by teddywilson** [BranchMetrics/android-branch-deep-linking#291]
Why do I need to use singleTask in my manifest? It seems as though when I use this, my main activity is called every time my app is opened--behavior which I don't want. Is using this attribute integral to the infrastructure of branch?

**Comment by sojanpr** [comment]
@teddywilson  Thanks for reaching out. Basically above has 2 questions 
1) Is `SingleTask` attribute is integral to the infra structure of Branch ?
     No. This attribute is not mandatory. It really  depends on your implementation and the way you want  the app to behave. If you are not specifying "SingleTask" for the activity receiving the deep link intent (The activity with Branch intent filter), that activity  will be launched as  a new instance. So you will see a new instance of your app is launched on clicking a Branch link. Since this is not expected for most of the partners we suggest to use `singleTask`

2) Main Activity is launched every time app is launched
     Since Main activity is specified as `singleTask` it will be launched each time app opens.  If you don't want this could you please try the following
 - Move Branch `intent-filter ` to the activity you really want to open on clicking a Branch Link
 - Make this activity as a `single task ` so that this activity will be launched up on clicking  a Branch link and then handle navigation in this activity.

**Comment by sojanpr** [comment]
@teddywilson Did the above helped to solve your issue. If so do you want to close  the issue?
