### ISSUE TITLE
API request /v1/profile missing parameter identity_id

### ISSUE THREAD

**Issue by anoop1304** [BranchMetrics/android-branch-deep-linking#316]
I have an phonegap project in which iOS platform is already integrated which is using the branch plugin and it is working fine. When i add the android platform in the same project then it is throwing an error from branch plugin.

When we start the app in android init() called properly after that it gives "API request /v1/profile missing parameter identity_id". I need your assistance for removing this error.

Thanks in advance

**Comment by sojanpr** [comment]
@anoop1304 We are sorry that you are facing this issue. We are working this and let you know as soon as possible.

**Comment by ethanneff** [comment]
Hello @anoop1304.

The [Branch Cordova/PhoneGap SDK](https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking) is a wrapper around the [Branch Android SDK](https://github.com/BranchMetrics/android-branch-deep-linking). They both are built ontop of the same code. I am not sure how you implemented the iOS platform, but I would strongly recommend you implement the Branch Cordova/PhoneGap SDK. In order to call **android init()**, you will need to call this in your Branch Cordova/PhoneGap SDK:
```js
Branch.initSession().then(function (res) {
    // console.log(res);
}).catch(function (err) {
    // console.log(res);
});
```

It also looks like you want to set a Branch Identity. This can also be achieved with *only* the Branch Cordova/PhoneGap SDK implemented:
```js
Branch.setIdentity("identity_name").then(function (res) {
  // console.log(res);
}).catch(function (err) {
  // console.error(err);
});
```

Is there a specific reason why you chose to implement the [Branch Android SDK](https://github.com/BranchMetrics/android-branch-deep-linking) that I may have overlooked?

**Comment by sojanpr** [comment]
@anoop1304 hope the above helped.
