### ISSUE TITLE
Fb messenger share link issue

### ISSUE THREAD

**Issue by spiritinlife** [BranchMetrics/android-branch-deep-linking#382]
When i share a branchUniversalObject to facebook messenger the link in the android mobile messenger app is not clickable and is not a link.
As you see in the image the https://vieno.app.link/jJHBcMz61z is not a link. 

![16121447_10207985315580007_518007996_o](https://cloud.githubusercontent.com/assets/6434983/22062709/b8c580da-dd83-11e6-8e52-06cbd8e47a59.png)

Notes: 
1) On desktop the link is displayed correctly.
2)  I use the default ShareSheetStyle for the sharing mechanism.

So is this related to you or should i contact facebook about this issue?
Thank you.

**Comment by EvangelosG** [comment]
Hi @spiritinlife -- thanks for the report! This is a known bug in Facebook messenger that we're working with their team to fix. In the meantime, please submit a bug report to Facebook. If you need a workaround: use a custom domain instead of app.link. Here's documentation to get you started on a custom domain: https://dev.branch.io/getting-started/link-domain-subdomain -- contact integrations@branch.io if you need help or have questions setting this up!

**Comment by Sunil-Limje** [comment]
Hi,
I am getting the same issue when we did  sharing the deep link using Facebook messenger. Is the issue has some confirmed working solution.

Thanks in advance!
Sunil

**Comment by EvangelosG** [comment]
Hi @Sunil-Limje -- the solution is still to use a custom domain, we have submitted the issue to FB a few times, still waiting to hear back. It would be great if you could submit the issue as well!

**Comment by dancherb** [comment]
When sharing a deep link via Messenger, I'm finding it opens in Messenger's custom browser as opposed to my app. You have to tap the 3 dots to get the "Open with..." dialogue to open it via my app (which obviously the user isn't going to figure out). Is there a way around this?

**Comment by ayyappantringapps** [comment]
@dancherb did you find any solution for the messenger issue ?
