### ISSUE TITLE
Branch Deep links opens app twice

### ISSUE THREAD

**Issue by arushijain45** [BranchMetrics/android-branch-deep-linking#392]
I am trying to open specific page on my app with branch deep link. While creating a link, I have set a key (say feedId) in deep linking section and add a value to it. I added following in android manifest file:

```
<activity android:name=".URLInterpreterActivity">

            <intent-filter android:autoVerify="true">
                <action android:name="android.intent.action.VIEW"/>
                <category android:name="android.intent.category.DEFAULT"/>
                <category android:name="android.intent.category.BROWSABLE"/>
                <data android:scheme="pqr" android:host="open"></data>
            </intent-filter>

            <meta-data android:name="io.branch.sdk.auto_link_keys" android:value="feedId" />

        </activity>
```

But when I click on branch link, it hits my activity twice, for the first time feedId is null and second time with feedId.

Please help why is this occuring and how to remove these two triggers?

**Comment by sojanpr** [comment]
@arushijain45., Thanks for reaching out. This seems more like an integration issue. You don't need to add metadata `io.branch.sdk.auto_link_keys` for simply deplaning to your activity. `auto_link_keys` are supposed to be used to open "another" activity than the deep linked activity up on a key match specified by `auto_link_keys`.
In your case the clicking the link it self opens the `URLInterpreterActivity` activity and then since  you have
 ` <meta-data android:name="io.branch.sdk.auto_link_keys" android:value="feedId" />` added to the same activity it open the `URLInterpreterActivity` again.  Not sure if you wanted to open a new Activity in this case 
For a faster response on integration issues could you please write to `<integrations@branch.io>`

**Comment by arushijain45** [comment]
Thanku sir for your well explanatory answer. As you said, I have removed meta data from manifest file. Now yes it opens activity only once but without deep link params i.e. feedId. I need this parameter for further processing. Can you please explain how to get it.

**Comment by EvangelosG** [comment]
Hi @arushijain45 -- glad you made some progress! Happy to help explain how to grab the parameter. Please reach out to integrations@branch.io and we'll dig right in. Include your manifest file and Branch related code!

**Comment by arushijain45** [comment]
Sir I have already mailed on the given address but had not got any response so far.

**Comment by EvangelosG** [comment]
Hi @arushijain45 -- great! I see it now, will follow up there with my previous requests.
