### ISSUE TITLE
Not working with twitter

### ISSUE THREAD

**Issue by arpitjoshi08** [BranchMetrics/android-branch-deep-linking#450]
i am using deeplinking with twitter share and when i click on link on twitter app , which was shared from our app its directly move on playstore to download app but app has already store and loged in. and this functionality properly working when i shared on facebook.

**Comment by EvangelosG** [comment]
Hi @arpitjoshi08 -- I'm unable to reproduce this issue with my test apps. Please review the following two sample projects: https://github.com/BranchMetrics/Android-Branch-Refer-A-Friend-Example
https://github.com/BranchMetrics/Branch-Example-Deep-Linking-Branchster-Android -- make sure you have implemented Branch correctly (check your manifest file, application class, activity). If you are still struggling, please write into integrations@branch.io and we can work with you 1:1. So far I've tested with a few links from native Twitter on Android and they are deep linking directly to my apps, so I'm suspecting a configuration error on your end.

**Comment by EvangelosG** [comment]
Hey arpitjoshi08 -- If you are referring to **mobile** Twitter on Android (using Twitter through the Chrome browser for example), I have some more information for you:

Unfortunately, this is a limitation of the Chrome browser and is triggered by the way that mobile web Twitter redirects to the link and there's nothing we can do to improve it. Basically, when clicking the link in the Twitter web app, they "fake click" (set window.location in JS) the link likely to handle tracking analytics and such. Chrome only supports opening up the app from a user-triggered link click, and fake clicks don't count. Chrome used to show a big fat error message here, but they added support to redirect to the Play Store only, which we now use.

Apologies but you've bumped into an edge case in the platform that we can't patch. We'll continue to monitor this situation and fix it once there's some way to do so. Fortunately, this should be a limited use case, since a majority of mobile users will just be inside Twitter's app.

**Comment by arpitjoshi08** [comment]
(https://github.com/BranchMetrics/Android-Branch-Refer-A-Friend-Example) this link working perfectly but getting  issue  in my app ,i am not understanding that why this occur. its happen only with twitter and working with app other like facebook, gmail etc.. and i matched my code with reference code its mostly same i think issue may be in setting on branch website.

**Comment by arpitjoshi08** [comment]
and one more issue is getting that i need to get successfully upload listener so i am using this code 
`branchUniversalObject.showShareSheet(getActivity(),
                linkProperties,
                shareSheetStyle,
                new Branch.BranchLinkShareListener() {
                    @Override
                    public void onShareLinkDialogLaunched() {
                    }

                    @Override
                    public void onShareLinkDialogDismissed() {
                    }

                    @Override
                    public void onLinkShareResponse(String sharedLink, String sharedChannel, BranchError error) {
                        if (error == null) {
                            Log.d(TAG, "success Data share");
                        //need to call webservice for update
                        }
                    }

                    @Override
                    public void onChannelSelected(String channelName) {
                    }
                }`
and  onLinkShareResponse listener always called when shared popoup open but there is no any guarantee that user will share or discard popup. so i need to call webservice on success of shared but i think there is no any method for that.

**Comment by EvangelosG** [comment]
Hey @arpitjoshi08 -- glad the test app is working for you! Here's the dashboard settings:
<img width="1215" alt="screen shot 2017-06-29 at 8 29 31 am" src="https://user-images.githubusercontent.com/3870241/27695948-29329452-5ca5-11e7-976c-cc1f790d09df.png">

As for the listener you're interested in: we can't listen for events beyond the user selecting an app to share to, as that app has now taken over inputs. If you shared to Twitter, then killed the twitter app before pressing post, we can't provide a share sheet process killer listener to capture that event. Don't get me wrong: it would be pretty cool. But it would also make Android a scary platform to support, or it would require outlandish permissions. One solution is that you could label your event here as "SHARE_CREATED" or since we're open source, clone the repo and add this functionality yourself. If you come across anything awesome, let me know and I'll review it!

**Comment by arpitjoshi08** [comment]
Hey  twitter redirection app issue has resolved now working properly. Actually issue was in twitter app i think, there was an older version installed in my device so it was not working with that , then i updated twitter app and check, it working properly and now redirect to my app if installed else move to playstore. thanks bro.

**Comment by EvangelosG** [comment]
Oh that makes me happy to hear, thanks for the update & you're welcome!
