### ISSUE TITLE
Update the docs to reflect how reopens are counted

### ISSUE THREAD

**Issue by makaroffandrey** [BranchMetrics/android-branch-deep-linking#451]
Your docs state that I should call `Branch$initSession()` every time the app is opened.
But what seems to happen is that processing of URL happens in `Branch$onIntentReady(Activity)` which is called in `BranchActivityLifeCycleObserver$onActivityResumed(Activity)`. Which means that I either have to wait for the `Activity` that handles the Branch URL to go up to `onResume()` in its lifecycle, or to pass URL to another activity that will be shown to the user.

This behaviour is not obvious from the docs, please change the docs to reflect that.

I did not want the activity that handles Branch links to be always shown to the user(only in some cases), therefore I was sometimes finishing it in `onCreate()` and lost referral info in open event.

**Comment by sojanpr** [comment]
@makaroffandrey Thank for your question. I think there is  a small confusion here. You need  to call Branch$initSession() only if you need the deep link parameters. Also your deep link activity need not to be the first activity that user see when they open the app in order to count reopens.

- Branch SDK watch the `ActivityLifeCycle` and when the app is opened (irrespective of which activity)  Branch start a session internally on the first activities `onResume()` method and collect the deep link params from Branch. 
- Session ends when your app goes to background
- You can get the deep link params any time in the session by using `Branch$initSession(callback)`  api.

Does the above answer your question. We will revisit the docs and make necessary corrections.

**Comment by makaroffandrey** [comment]
@sojanpr Here is my setup:
I have Splash Activity that handles all http links to my app and also responds to `android.intent.category.LAUNCHER` intents and has `android:launchMode="singleTask"`. This activity also calls `Branch$initSession(callback)`.
When the app starts for the first time, Splash opens, does some initialization stuff and then opens another activity(let's call it activity `A`). So the activity stack looks like this:
`Splash -> A`
Since I do not want the user to navigate back to Splash, immediately after starting activity `A`, Splash calls `finish()` on itself so the stack contains only activity `A`. The user then is able to navigate to other activities in standard android fashion so let's say the activity stack becomes like this:
`A -> B -> C`
If the user then goes into browser and clicks on my link, the intent opens Splash activity again.  So the stack become like this:
`A -> B -> C -> Splash`
The splash does not need to do any initialization stuff in this case, so I was finishing it in `onCreate()`. And since it never got to `onResume()`, I did not get info about which link was clicked in Branch dashboard.

I had to go through Branch code to understand that i was finishing activity too early, and that I have to wait until `onCreate()`.

I think it will be beneficial to all if the documentation will clearly state that if you need to get link info in your branch dashboard, then you have to wait until `onResume()` is called on an `Activity` where you are calling `Branch$initSession(callback)`

**Comment by EvangelosG** [comment]
Glad you went through the code and figured out your issue. We suggest calling initSession from onStart vs onResume, and yes do not finish your activity before a callback is hit :).
