### ISSUE TITLE
generateShortUrl is not called after application is downloaded from Google Play

### ISSUE THREAD

**Issue by galisamas** [BranchMetrics/android-branch-deep-linking#471]
Hello,

Have problems with the branch.io when first time new session is initialised. When creating BranchUniversalObject() in the first session (the application is just downloaded from the google play) method generateShortUrl(...) is never called. But after restarting the application it starts working well. So the issue is when the first time downloaded application is skipping the generateShortUrl(...) method. 

It only happens with google play downloaded application (never had the same issue with debug, prod or even apk file downloaded from the google play console).

Lastly, I noticed that it issue happens only with the cheeper phones as Huawei, leeco etc.

**Comment by EvangelosG** [comment]
Hi @galisamas -- thanks for writing in. We'll need more specifics from you to dig into this issue. Please e-mail integrations@branch.io with your branch key to get started. Also please provide Branch related code blocks and the locations of said code blocks (onResume vs onStart vs onCreate etc).

**Comment by EvangelosG** [comment]
Looks like galisamas is proceeding from his deep linking activity to his main app after waiting for 2 seconds, instead of waiting for the init session callback block to be executed. This is why generating a link works sometimes, but not all the time, and especially not on older devices which will take longer to execute http requests. The issue is unrelated to Branch's SDK, we're crafting a response now to help guide galisamas to his solution. If any SDK bugs are found I will loop back and open this thread with our findings. As a few other people have posted about this before, let me be clear: you cannot kill the activity you're using to init Branch before init has completed.
