### ISSUE TITLE
$deeplink_path not working in custom webview

### ISSUE THREAD

**Issue by krcho** [BranchMetrics/android-branch-deep-linking#472]
We use Branch Link in our own new article for DeepLinking And it WAS worked.
that link is "https://bbq1.app.link/Dtiv6pBPwB?$deeplink_path=viewStock%3Fcode%3DA005070%26tabIndex%3D0%26subTabIndex%3D0"

But, It doesn't work now. there is no change in source code !
And, It works on Chrome browser or KakaoTalk In app browser. I don't know why;; 
+ iOS worked.
+ Only in Android issue

is there any change in deep linking program???

**Comment by krcho** [comment]
our service link is 
https://robonews.dunamu.com/articles/42876

**Comment by EvangelosG** [comment]
Hi @krcho -- the link you posted as well as links I'm testing from your Dashboard are launching the app and deep linking to content which is revealed and then hidden a few milliseconds later. If you are saying that links do not redirect properly in-app from a webview widget, this is expected behavior. Out of the box we do not support in-app routing through webviews. The better solution would be to use Intents for local in-app routing. I assume you might be rendering HTML content containing Branch links in your webview, if this is the case you could build a custom webview widget which returns the URL it's trying to load, then scrape this URL for link content and route in-app accordingly. This is a custom solution which I can suggest but not support. If you require assistance configuring $deeplink_path -- please contact integrations@branch.io and our awesome team will help you out!
