### ISSUE TITLE
Rare crash in PackageManager

### ISSUE THREAD

**Issue by tmtrademarked** [BranchMetrics/android-branch-deep-linking#488]
We use the Branch SDK in our app, and have gotten a few rare crashes when starting our application. We're calling `Branch.getAutoInstance(this)` in the `onCreate` method of our application - and it occasionally results in the following crash:

```
Exception java.lang.RuntimeException: Unable to create application com.blueapron.mobile.ui.MobileApplication: java.lang.RuntimeException: Package manager has died
android.app.ActivityThread.handleBindApplication (ActivityThread.java:6319)
android.app.ActivityThread.access$1800 (ActivityThread.java:221)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:1860)
android.os.Handler.dispatchMessage (Handler.java:102)
android.os.Looper.loop (Looper.java:158)
android.app.ActivityThread.main (ActivityThread.java:7224)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1230)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1120)
arrow_drop_down
Caused by java.lang.RuntimeException: Package manager has died
android.app.ApplicationPackageManager.getApplicationInfo (ApplicationPackageManager.java:365)
io.branch.referral.PrefHelper.readBranchKey (PrefHelper.java:306)
io.branch.referral.Branch.getBranchInstance (Branch.java:551)
io.branch.referral.Branch.getAutoInstance (Branch.java:629)
com.blueapron.service.ui.BlueApronApplication.configureBranch (BlueApronApplication.java:139)
com.blueapron.service.ui.BlueApronApplication.onCreate (BlueApronApplication.java:85)
android.app.Instrumentation.callApplicationOnCreate (Instrumentation.java:1036)
android.app.ActivityThread.handleBindApplication (ActivityThread.java:6316)
android.app.ActivityThread.access$1800 (ActivityThread.java:221)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:1860)
android.os.Handler.dispatchMessage (Handler.java:102)
android.os.Looper.loop (Looper.java:158)
android.app.ActivityThread.main (ActivityThread.java:7224)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1230)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1120)
arrow_drop_down
Caused by android.os.DeadObjectException:
android.os.BinderProxy.transactNative (BinderProxy.java)
android.os.BinderProxy.transact (BinderProxy.java:503)
android.content.pm.IPackageManager$Stub$Proxy.getApplicationInfo (IPackageManager.java:2945)
android.app.ApplicationPackageManager.getApplicationInfo (ApplicationPackageManager.java:356)
io.branch.referral.PrefHelper.readBranchKey (PrefHelper.java:306)
io.branch.referral.Branch.getBranchInstance (Branch.java:551)
io.branch.referral.Branch.getAutoInstance (Branch.java:629)
com.blueapron.service.ui.BlueApronApplication.configureBranch (BlueApronApplication.java:139)
com.blueapron.service.ui.BlueApronApplication.onCreate (BlueApronApplication.java:85)
android.app.Instrumentation.callApplicationOnCreate (Instrumentation.java:1036)
android.app.ActivityThread.handleBindApplication (ActivityThread.java:6316)
android.app.ActivityThread.access$1800 (ActivityThread.java:221)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:1860)
android.os.Handler.dispatchMessage (Handler.java:102)
android.os.Looper.loop (Looper.java:158)
android.app.ActivityThread.main (ActivityThread.java:7224)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1230)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1120)
```

From what I can tell, this may be related to the app being updated in the background, or other such oddities. It might be worth considering catching `RuntimeException` in the usage of PackageManager here - especially because it looks like `getBranchInstance` will fall back to using the string ID provided in the APK.

**Comment by sojanpr** [comment]
@tmtrademarked thanks for the trace.  Can you please tell us which SDK version  you are using? We have fixed a similar issue with v2.4.5

**Comment by sojanpr** [comment]
@tmtrademarked is there any chance that your app has more than one process that can hold the package manager. The error looks more likely the ApplicaitonInfo object is being accessed by two process similar to this issue
https://github.com/googlemaps/android-maps-utils/issues/382

**Comment by tmtrademarked** [comment]
This was reported in a build using 2.10.0 - we've updated to 2.12.0, but haven't released that build yet.

We don't directly use multiple processes in our app, but we use several SDKs that are capable of spinning up background processes. Various tools like crash reporting, experimentation, etc could be running background processes. But I'm not totally sure I understand why that would cause this issue - could you elaborate slightly?

**Comment by sojanpr** [comment]
From the logs it looks like issue was caused by a dead package manager object. So before Branch try to access the package manager it is dead due to some reason.
```Caused by android.os.DeadObjectException:
android.os.BinderProxy.transactNative (BinderProxy.java)
android.os.BinderProxy.transact (BinderProxy.java:503)
android.content.pm.IPackageManager$Stub$Proxy.getApplicationInfo (IPackageManager.java:2945)
android.app.ApplicationPackageManager.getApplicationInfo (ApplicationPackageManager.java:356)```

Possible causes
1. `TransactionTooLargeException` cause by any other part of the code : We have noticed that there is a 1MB limit for binder transactions. If in any case there is a Binder transcation exceeding this limit will kill package manager. This will lead to a dead object exception for any other code which try to access package manager .

2.  Application Info Exceed Binder limit. This may be another reason when the application has many activities and metadata in the manifest. We have seen this happening in one case with Branch and added a crash protection.
https://github.com/BranchMetrics/android-branch-deep-linking/blob/master/Branch-SDK/src/io/branch/referral/Branch.java#L2867

We will check and add a crash protection for this issue if it caused  by 2.

**Comment by BobyIlea** [comment]
Hello everyone, we are also getting a crash that seems to be related to a dead package manager. In our case the crash always happens as a result of:
`io.branch.referral.Branch.registerAppInit(Branch.java:2272)` which eventually calls
`io.branch.referral.SystemObserver.getAppVersion(SystemObserver.java:214)` and then
`android.app.ApplicationPackageManager.getPackageInfo`.

We're not sure if by the time those calls happen the package manager is already dead or those actual calls are the ones killing it(since we only get this crash as a result of those calls).

I know that calling `ApplicationPackageManager.getPackageInfo` with many flags at once may cause the killing of the package manager, so you might want to remove unused flags from the call(if there are any) or break the call into multiple calls with different flags(more info here: https://developer.android.com/reference/android/content/pm/PackageManager.html#getPackageInfo(java.lang.String,%20int) )

One other thing regarding this crash: it seems to happen on Amazon devices running Android 4(4.4.3). I'll also attach the logs we have here.

[com.amazon.megarama.slotsape_issue_88_crash.txt](https://github.com/BranchMetrics/android-branch-deep-linking/files/1498749/com.amazon.megarama.slotsape_issue_88_crash.txt)

**Comment by sojanpr** [comment]
@BobyIlea We don't see any flags to optimize in the call `ApplicationPackageManager.getPackageInfo` in SDK. We are still looking into the reason for the crash and reproduce it. Will update you soon

**Comment by sojanpr** [comment]
Added a proactive crash protection to the SDK by handling exception from package manager
