### ISSUE TITLE
In the Share Dialog, not the correct option is highlighted

### ISSUE THREAD

**Issue by smart-fun** [BranchMetrics/android-branch-deep-linking#540]
Hello,

When I want to share some link with Branch, a dialog opens with options like Facebook, Gmail...
When I click on an option (like Facebook), the Facebook app is correctly started but the highlighted option is not the one I clicked in the dialog: the option AFTER Facebook is highlighted.
I'm using sdk 2.14.5 on Samsung S4 running Android 5.0.1.
Same with Emulator running Android 7.0

**Comment by sojanpr** [comment]
@smart-fun Thanks for reaching out. Unfortunately we are  not  able to reproduce  this issue. Could you please help with the  following in order to debug more into this
1) Can you please run the Test-Bed application added to this repo and see if you face the same issue
2) Do you have an option added for "Copy URL" and "Show More" option?

**Comment by ibogolyubskiy** [comment]
Can be reproduced in the Test-Bed application.
Options "Copy URL" and "Show More" are added.
The problem is when using headers in a ListView they are also considered as items in the onItemClickListener, so you need to subtract the number of added headers from the current position to get REAL clicked position in ListView.
Like that:
      adapter.selectedPos = pos - shareOptionListView.getHeaderViewsCount();

See [PR](https://github.com/BranchMetrics/android-branch-deep-linking/pull/544).

**Comment by sojanpr** [comment]
@ibogolyubskiy Thanks for the PR. Will review and add it with next release.

**Comment by sojanpr** [comment]
The fix in the PR LGTM. Moved to a new PR created against staging 
https://github.com/BranchMetrics/android-branch-deep-linking/pull/566
Will be added  two the next SDK version
