### ISSUE TITLE
Valid deep link returns no parameters in integration tests

### ISSUE THREAD

**Issue by NeverwinterMoon** [BranchMetrics/android-branch-deep-linking#561]
So, I was trying to write some integration tests for Branch deep links. I actually did this before with ease for the iOS project using exactly the same test data. I use instrumented tests, and I basically call Branch.init `branch.initSession(callback, uri, activity)` where URI is an existing link. What I always get in callback is this: `{"+clicked_branch_link":false,"+is_first_session":false}`. Every time.

I also noticed that I can get the same result in the actual running application if I have the app on the foreground, and then I pass the link using `adb shell am start -W -a android.intent.action.VIEW -d "`.  If I move the app to background and use the aforementioned `adb` command, it works fine and returns the actual parameters. In all this cases I use one and the same pre-generate link.

**Comment by sojanpr** [comment]
@NeverwinterMoon Branch SDK calls the Branch server and get the params when the very first  activity is opened. It uses the URI in the very first activity to get the param (This is because Branch want to deliver params when app is opened through a link click). Any call to init session after this will  get the params received for first activity.

Please try this approach if you want to get params for a  link if app is already running.
https://github.com/BranchMetrics/android-branch-deep-linking/issues/241#issuecomment-373310981

**Comment by NeverwinterMoon** [comment]
@sojanpr In the discussion around the comment you linked you say:

> Unfortunately SDK doesn't support init again in the same activity.

But in my case, I don't do that. In my SplashActivity, I actually check the intent.data - if it's null, I don't call Branch init. So, when I launch the app, not from a link, I don't call Branch init. Then I send the link through `adb` and this is the first time the activity calls Branch init.

Also, you haven't commented on my integration test situation - where I don't make any calls except the Branch init, it's a isolated test, so I call init only once and still get `{"+clicked_branch_link":false,"+is_first_session":false}`

**Comment by sojanpr** [comment]
@NeverwinterMoon Even if you don't call initSession from your code SDK will call init session automatically when the first activity is launched. Further init session calls  from your app will be server with the deep link data got for first activities URI data
