### ISSUE TITLE
URL missing when containing 'password'

### ISSUE THREAD

**Issue by charlespernet** [BranchMetrics/android-branch-deep-linking#562]
I have an Android web view and found an issue using Branch doing this :
1) initialized Branch according to the [documentation](https://docs.branch.io/pages/apps/android/) with : 
```java
Branch.getInstance().initSession(new Branch.BranchReferralInitListener() {
            @Override
            public void onInitFinished(JSONObject referringParams, BranchError error) {
                if (error == null) {
                    Log.i("BRANCH", referringParams.toString());
                } else {
                    Log.i("BRANCH", error.getMessage());
                }
            }
        }, this.getIntent().getData(), this);
```

2) Tested few links and checked my BRANCH logger

**Exemple 1** : https://mywebsite.com/random
```
I/BRANCH: {"+non_branch_link":"https:\/\/mywebsite.com\/random », »+clicked_branch_link":false,"+is_first_session":false}
```
Which is pretty much what I expected

**Exemple 2** : https://mywebsite.com/users/password/edit?reset_password_token=***

`I/BRANCH: {"+clicked_branch_link":false,"+is_first_session":false}`

As if there is no branch link

**Exemple 3** : https://mywebsite.com/users/passwor/edit?reset_passwor_token=***
```
I/BRANCH: {"+non_branch_link":"https:\/\/mywebsite.com\/users\/passwor\/edit\?reset_passwor_token=*** », »+clicked_branch_link":false,"+is_first_session":false}
````

It behaves as if when my Url contains 'password', Branch gets rid of it, is it something known?
I would like to get the whole Url as a non branch link even in exemple 2.

Not really sure about what I am missing here.

**Comment by ethanneff** [comment]
Hello @charlespernet,

Yes, you are correct.

We have filters within our gateway which prevent developers from sending us confidential data. `Password` is one of these filters. We do this for security reasons. We don't want developers accidentally send us plaintext passwords, private tokens, etc. This could compromise us as well as your users.

Since Branch deep links can be shared quite easily, we typically don't recommend passing sensitive data through them.

I see you are passing a token instead of a user password. This is fine. I would recommend removing the keyword `password` to prevent it from being dropped by our system.

Thanks,

**Comment by charlespernet** [comment]
Thank you for you quick Answer !

That was pretty much what I assumed.
I was wondering if there was by any chance a way to custom the regexp used for filtering, It could be handy.

For now I will get those links out of branch.

Thanks again for you quick feedback, I think we can close this issue.
