### ISSUE TITLE
Are FB SDK proguard rules in the README up-to-date?

### ISSUE THREAD

**Issue by alessandrocandolini** [BranchMetrics/android-branch-deep-linking#615]
ProGuard/R8 rules for Facebook SDK to support deep linking through Facebook ads read
`-keep class com.facebook.applinks.** { *; }
-keepclassmembers class com.facebook.applinks.** { *; }
-keep class com.facebook.FacebookSdk { *; }`

These rules basically force ProGuard/R8 to not process anything inside the whole FB SDK and applinks packages. It would be nice from optimisation point of view if it were possible to relax these conditions. 

Also, afaik, Facebook Android SDKs >= 4.12 has built-in fine-tuned ProGuard configurations so there should be no need to specify them explicitly 

Can the rules be relaxed/removed? Is the readme file up-to-dated?

**Comment by csalmi-branch** [comment]
@alessandrocandolini Thanks for bringing this issue up! Is this currently causing you any trouble while using the branch SDK? The readme is currently up to date, and we will backlog a ticket to re-assess the proguard configuration in relation to the FB SDK. Just to help us investigate this issue, could you provide us with the impacts you are seeing due to this issue, and the version of the Branch android SDK?

**Comment by csalmi-branch** [comment]
Due to the age of this issue, I am closing this now. If you are encountering this problem still, please reach out to our support team (support.branch.io) or open a new github issue and we would be happy to help you out!
